# Generated by Django 5.2.3 on 2025-07-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.CharField(max_length=700),
        ),
    ]
