# Generated by Django 5.2.3 on 2025-07-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('date', models.ImageField(upload_to='', verbose_name='hw/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
